name: Helm Chart Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  HELM_CHART_NAME: 'grupo118fase4'
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

jobs:
    publish-helm-chart:
        runs-on: ubuntu-latest
        steps:
          - name: Log in to Azure Container Registry
            if: (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main') && github.event_name == 'push'
            uses: docker/login-action@v3
            with:
              registry: ${{ env.REGISTRY }}
              username: ${{ env.ACR_USERNAME }}
              password: ${{ env.ACR_PASSWORD }}            

          - name: Set up Helm
            if: (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main') && github.event_name == 'push'
            uses: azure/setup-helm@v3
            with:
              version: '3.12.0'

          - name: Package Helm chart
            if: (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main') && github.event_name == 'push'    
            run: |
              VERSION="1.0.${{ github.run_number }}"
              helm package ./helm/${{ env.HELM_CHART_NAME }} --version $VERSION
              echo "HELM_VERSION=$VERSION" >> $GITHUB_ENV

          - name: Push Helm chart to ACR
            if: (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main') && github.event_name == 'push'
            run: |
              helm registry login ${{ env.REGISTRY }} --username ${{ env.ACR_USERNAME }} --password ${{ env.ACR_PASSWORD }}
              helm push ${{ env.HELM_CHART_NAME }}-${{ env.HELM_VERSION }}.tgz oci://${{ env.REGISTRY }}/helm   